const PRESETS=[{name:'美式咖啡',category:'咖啡',volume:350,caffeine:150,emoji:'☕'},{name:'拿铁',category:'咖啡',volume:350,caffeine:75,emoji:'🥛'},{name:'手冲咖啡',category:'咖啡',volume:300,caffeine:120,emoji:'🫖'},{name:'水',category:'水',volume:500,caffeine:0,emoji:'💧'},{name:'绿茶',category:'茶',volume:400,caffeine:35,emoji:'🍵'},{name:'果汁',category:'果汁',volume:300,caffeine:0,emoji:'🍊'}];
const CATEGORIES={咖啡:'☕',茶:'🍵',水:'💧',奶类:'🥛',果汁:'🍊',汽水:'🥤',其他:'🥂'};
const BRAND_CATALOG=[
{brand:'瑞幸咖啡',type:'咖啡',drinks:[['生椰拿铁',480,80],['酱香拿铁',480,75],['陨石拿铁',480,80],['厚乳拿铁',480,80],['橙C美式',480,120],['标准美式',480,150],['抹茶好喝椰',480,30]]},
{brand:'库迪咖啡',type:'咖啡',drinks:[['潘帕斯蓝生酪拿铁',480,75],['生椰拿铁',480,80],['米乳拿铁',480,75],['厚乳拿铁',480,80],['经典美式',480,150],['橙C美式',480,120]]},
{brand:'Manner Coffee',type:'咖啡',drinks:[['冰美式',360,150],['热美式',300,150],['燕麦拿铁',360,80],['桂花拿铁',360,80],['澳白',240,110],['浓缩咖啡',60,75]]},
{brand:'星巴克中国',type:'咖啡',drinks:[['拿铁（大杯）',473,150],['美式咖啡（大杯）',473,225],['馥芮白（大杯）',473,195],['焦糖玛奇朵（大杯）',473,150],['冷萃冰咖啡（大杯）',473,205],['抹茶星冰乐（大杯）',473,70]]},
{brand:'Seesaw Coffee',type:'咖啡',drinks:[['长颈鹿美式',450,150],['云南风味拿铁',450,80],['椰子冷萃',450,150],['澳白',240,110]]},
{brand:'喜茶',type:'茶',drinks:[['多肉葡萄',650,35],['芝芝莓莓',650,35],['烤黑糖波波牛乳',500,0,'奶类'],['绿妍轻乳茶',500,40],['水牛乳双拼波波',500,0,'奶类'],['椰椰芒芒',650,0,'果汁']]},
{brand:'奈雪的茶',type:'茶',drinks:[['霸气芝士草莓',650,35],['霸气橙子',650,35],['茉莉初雪',500,40],['杨枝甘露',500,0],['霸气葡萄',650,35],['金色山脉珍珠奶茶',500,40]]},
{brand:'霸王茶姬',type:'茶',drinks:[['伯牙绝弦',500,60],['桂馥兰香',500,60],['万里木兰',500,55],['青青糯山',500,55],['花田乌龙',500,55],['去云南·玫瑰普洱',500,55]]},
{brand:'蜜雪冰城',type:'茶',drinks:[['冰鲜柠檬水',700,0,'其他'],['珍珠奶茶',500,35],['满杯百香果',700,20],['棒打鲜橙',700,0,'果汁'],['茉莉奶绿',500,35],['雪王大圣代',350,0,'奶类']]},
{brand:'茶百道',type:'茶',drinks:[['杨枝甘露',650,0],['豆乳玉麒麟',500,40],['招牌芋圆奶茶',500,35],['西瓜啵啵',650,20],['茉莉奶绿',500,40],['超级杯水果茶',700,35]]},
{brand:'CoCo都可',type:'茶',drinks:[['珍珠奶茶',500,35],['鲜芋青稞牛奶',500,0,'奶类'],['百香双响炮',650,30],['柠檬霸',650,30],['茉香奶茶',500,40],['莓莓果茶',650,25]]},
{brand:'一点点',type:'茶',drinks:[['四季奶青',500,40],['波霸奶茶',500,35],['冰淇淋红茶',500,45],['柠檬养乐多',500,0],['红茶玛奇朵',500,45],['阿华田',500,0,'奶类']]},
{brand:'沪上阿姨',type:'茶',drinks:[['血糯米奶茶',500,35],['杨枝甘露',650,0],['茉莉奶绿',500,40],['多肉葡萄',650,30],['芋泥波波奶茶',500,35]]},
{brand:'古茗',type:'茶',drinks:[['超A芝士葡萄',650,35],['云岭茉莉白',500,40],['大叔奶茶',500,35],['杨枝甘露椰奶',650,0],['芝士多肉桃桃',650,30]]},
{brand:'农夫山泉',type:'水',drinks:[['饮用天然水',550,0],['东方树叶茉莉花茶',500,0,'茶'],['东方树叶青柑普洱',500,0,'茶'],['茶π柚子绿茶',500,25,'茶'],['尖叫运动饮料',550,0,'其他'],['NFC橙汁',300,0,'果汁']]},
{brand:'元气森林',type:'汽水',drinks:[['白桃味气泡水',480,0],['青柠味气泡水',480,0],['可乐味气泡水',480,0],['外星人电解质水',500,0,'水'],['乳茶',450,25,'奶类']]},
{brand:'娃哈哈',type:'其他',drinks:[['AD钙奶',220,0,'奶类'],['营养快线',500,0,'奶类'],['纯净水',596,0,'水'],['非常可乐',500,45,'汽水']]},
{brand:'统一',type:'茶',drinks:[['阿萨姆奶茶',500,35],['冰红茶',500,25],['绿茶',500,25],['鲜橙多',450,0,'果汁']]},
{brand:'康师傅',type:'茶',drinks:[['冰红茶',500,25],['茉莉蜜茶',500,25],['茉莉清茶',500,25],['酸梅汤',500,0,'其他']]}];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let entries=loadEntries();
function loadEntries(){try{return JSON.parse(localStorage.getItem('siplog.entries')||'[]')}catch{return[]}}function persist(){localStorage.setItem('siplog.entries',JSON.stringify(entries));renderAll()}function localDay(v){const d=new Date(v);return d.getFullYear()+'-'+(d.getMonth()+1)+'-'+d.getDate()}function isToday(v){return localDay(v)===localDay(new Date())}function esc(s=''){const d=document.createElement('div');d.textContent=s;return d.innerHTML}function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove('show'),1800)}function formatTime(v){return new Intl.DateTimeFormat('zh-CN',{hour:'2-digit',minute:'2-digit'}).format(new Date(v))}function dateTitle(v){const d=new Date(v),t=new Date(),y=new Date();y.setDate(t.getDate()-1);if(localDay(d)===localDay(t))return'今天';if(localDay(d)===localDay(y))return'昨天';return new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'short'}).format(d)}function inputDate(date=new Date()){const d=new Date(date.getTime()-date.getTimezoneOffset()*60000);return d.toISOString().slice(0,16)}function newId(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()}
function init(){
$('#today-date').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(new Date());
$('#drink-category').innerHTML=Object.keys(CATEGORIES).map(c=>'<option>'+c+'</option>').join('');
$('#brand-select').innerHTML='<option value="">选择品牌</option>'+BRAND_CATALOG.map((b,i)=>'<option value="'+i+'">'+b.brand+'</option>').join('');
$('#quick-grid').innerHTML=PRESETS.slice(0,4).map((p,i)=>'<button class="quick-card" data-preset="'+i+'"><span class="emoji">'+p.emoji+'</span><strong>'+p.name+'</strong><small>'+p.volume+' ml</small></button>').join('');
$('#preset-strip').innerHTML=PRESETS.map((p,i)=>'<button type="button" class="preset-pill" data-dialog-preset="'+i+'"><span>'+p.emoji+'</span>'+p.name+'</button>').join('');
$$('.quick-card').forEach(b=>b.onclick=()=>quickAdd(PRESETS[+b.dataset.preset]));$$('.preset-pill').forEach(b=>b.onclick=()=>fillPreset(PRESETS[+b.dataset.dialogPreset]));$('#brand-select').onchange=updateBrandDrinks;$('#brand-drink-select').onchange=applyBrandDrink;$$('.tab[data-screen]').forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));$('#main-add').onclick=$('#custom-add').onclick=()=>openForm();$('.dialog-cancel').onclick=()=>$('#drink-dialog').close();$('#drink-form').onsubmit=saveForm;$('#history-search').oninput=renderHistory;$('#export-button').onclick=()=>$('#backup-dialog').showModal();$('.backup-close').onclick=()=>$('#backup-dialog').close();$('#download-backup').onclick=exportBackup;$('#import-backup').onchange=importBackup;renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js')}
function showScreen(n){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===n+'-screen'));$$('.tab[data-screen]').forEach(t=>t.classList.toggle('active',t.dataset.screen===n));scrollTo(0,0);if(n==='history')renderHistory();if(n==='insights')renderInsights()}
function quickAdd(p){entries.unshift({id:newId(),...p,date:new Date().toISOString(),note:''});persist();toast('已记录 '+p.name)}function fillPreset(p){$('#drink-name').value=p.name;$('#drink-category').value=p.category;$('#drink-volume').value=p.volume;$('#drink-caffeine').value=p.caffeine}
function openForm(p=PRESETS[0]){fillPreset(p);$('#brand-select').value='';$('#brand-drink-select').innerHTML='<option value="">选择饮品</option>';$('#brand-drink-select').disabled=true;$('#drink-time').value=inputDate();$('#drink-note').value='';$('#drink-dialog').showModal()}
function updateBrandDrinks(){const i=$('#brand-select').value,s=$('#brand-drink-select');if(i===''){s.disabled=true;s.innerHTML='<option value="">选择饮品</option>';return}const b=BRAND_CATALOG[+i];s.disabled=false;s.innerHTML='<option value="">选择饮品</option>'+b.drinks.map((d,j)=>'<option value="'+j+'">'+d[0]+'</option>').join('')}
function applyBrandDrink(){const bi=$('#brand-select').value,di=$('#brand-drink-select').value;if(bi===''||di==='')return;const b=BRAND_CATALOG[+bi],d=b.drinks[+di],c=d[3]||b.type;$('#drink-name').value=b.brand+' · '+d[0];$('#drink-category').value=c;$('#drink-volume').value=d[1];$('#drink-caffeine').value=d[2]}
function saveForm(e){e.preventDefault();entries.unshift({id:newId(),name:$('#drink-name').value.trim(),category:$('#drink-category').value,volume:+$('#drink-volume').value||0,caffeine:+$('#drink-caffeine').value||0,date:new Date($('#drink-time').value).toISOString(),note:$('#drink-note').value.trim()});persist();$('#drink-dialog').close();toast('记录已保存')}
function entryHTML(e){return '<article class="entry"><div class="entry-icon">'+(CATEGORIES[e.category]||'🥂')+'</div><div class="entry-copy"><strong>'+esc(e.name)+'</strong><small>'+formatTime(e.date)+(e.note?' · '+esc(e.note):'')+'</small></div><div class="entry-values"><strong>'+e.volume+' ml</strong>'+(e.caffeine?'<small>'+e.caffeine+' mg 咖啡因</small>':'')+'</div><button class="delete-entry" data-delete="'+e.id+'" aria-label="删除">×</button></article>'}
function bindDeletes(root){root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('删除这条饮品记录？')){entries=entries.filter(e=>e.id!==b.dataset.delete);persist();toast('记录已删除')}})}
function renderToday(){const l=entries.filter(e=>isToday(e.date)).sort((a,b)=>new Date(b.date)-new Date(a.date)),v=l.reduce((s,e)=>s+e.volume,0),c=l.reduce((s,e)=>s+e.caffeine,0);$('#cup-count').textContent=l.length+' 杯';$('#total-volume').textContent=v;$('#total-caffeine').textContent=c;$('#water-progress').style.width=Math.min(v/2000*100,100)+'%';$('#goal-copy').textContent=v>=2000?'今天的饮用目标已完成，真不错。':'距离 2000 ml 目标还有 '+(2000-v)+' ml';const r=$('#today-list');r.innerHTML=l.length?l.map(entryHTML).join(''):'<div class="empty"><span>☕</span><b>还没有记录</b><span>点一下下方的 ＋，记下今天的第一杯吧</span></div>';bindDeletes(r)}
function groupByDay(list){return list.reduce((a,e)=>((a[localDay(e.date)]??=[]).push(e),a),{})}function renderHistory(){const q=$('#history-search').value.trim().toLowerCase(),l=entries.filter(e=>!q||e.name.toLowerCase().includes(q)||e.category.includes(q)),g=groupByDay(l),r=$('#history-list');r.innerHTML=Object.entries(g).sort(([a],[b])=>b.localeCompare(a)).map(([,items])=>'<section class="day-group"><div class="day-head"><span>'+dateTitle(items[0].date)+'</span><span>'+items.reduce((s,e)=>s+e.volume,0)+' ml</span></div><div class="entry-list">'+items.sort((a,b)=>new Date(b.date)-new Date(a.date)).map(entryHTML).join('')+'</div></section>').join('')||'<div class="empty"><b>暂无记录</b><span>喝过的饮品会出现在这里</span></div>';bindDeletes(r)}
function renderInsights(){const days=[];for(let i=6;i>=0;i--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);days.push(d)}const vals=days.map(d=>entries.filter(e=>localDay(e.date)===localDay(d)).reduce((s,e)=>s+e.volume,0)),max=Math.max(...vals,2000);$('#week-chart').innerHTML=days.map((d,i)=>'<div class="bar-column"><div class="bar" title="'+vals[i]+' ml" style="height:'+Math.max(vals[i]/max*145,3)+'px"></div><small>'+'日一二三四五六'[d.getDay()]+'</small></div>').join('');const we=entries.filter(e=>days.some(d=>localDay(e.date)===localDay(d))),total=we.reduce((s,e)=>s+e.volume,0);$('#week-total').textContent='共 '+total+' ml';$('#daily-average').textContent=Math.round(total/7);$('#week-caffeine').textContent=we.reduce((s,e)=>s+e.caffeine,0);const counts={};we.forEach(e=>counts[e.category]=(counts[e.category]||0)+1);$('#category-list').innerHTML=Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([c,n])=>'<div class="category-row"><span>'+(CATEGORIES[c]||'🥂')+'</span><strong>'+c+'</strong><span>'+n+' 杯</span></div>').join('')||'<p class="muted">记录几杯后，这里会显示你的饮用偏好。</p>'}
function renderAll(){renderToday();renderHistory();renderInsights()}function exportBackup(){const blob=new Blob([JSON.stringify({app:'SipLog',version:1,exportedAt:new Date().toISOString(),entries},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='饮刻备份-'+localDay(new Date()).replaceAll('-','')+'.json';a.click();URL.revokeObjectURL(a.href);toast('备份已导出')}async function importBackup(ev){const f=ev.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text());if(!Array.isArray(d.entries))throw Error();if(confirm('将导入 '+d.entries.length+' 条记录，是否继续？')){entries=d.entries;persist();$('#backup-dialog').close();toast('备份导入成功')}}catch{alert('无法读取这个备份文件')}ev.target.value=''}init();